spring.datasource.url=jdbc:postgresql://ep-broad-bar-ai75xvy4-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7znhfy5NLxer
spring.jpa.hibernate.ddl-auto=update

spring.application.name=escontroEJC
